/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Menu_PlayerList: typeof import('./src/components/menu_PlayerList.vue')['default']
    Menu_PlayerList_Item: typeof import('./src/components/menu_PlayerList_Item.vue')['default']
    Menu_RoomList: typeof import('./src/components/menu_RoomList.vue')['default']
    Menu_RoomList_Item: typeof import('./src/components/menu_RoomList_Item.vue')['default']
    Piece: typeof import('./src/components/game/piece.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
  }
}
